title: Anabel Jiménez 
logo: /assets/profile_pic.jpeg <mi cara>
#description: Con experiencia práctica en procesos ETL, Machine Learning, su implementación, optimización, evaluación y validación de desempeño. Tengo experiencia en Gobernanza de datos, Automatización de tareas y optimización de procesos, así como en herramientas para la visualización de datos en tiempo real.

description_en: Professional with hands-on experience in ETL processes, Machine Learning, implementation, optimisation, evaluation and performance validation. I have experience in Data Governance,  Task Automation and process optimisation as well as real-time data visualisation tools. Eager to contribute and learn in a dynamic data-driven environment.

competencies: Python, SQL, PySpark, Machine Learning, Powerbi, Looker, Big Data, Cloud Platforms(GCP, AWS).

images:
  - image1: /Assets/kaggle2.jpg
  - image2: /Assets/linkedin.jpg

profile_pic: /Assets/profile_mine.jpeg

# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

